### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.internal.SessionState'

### ISSUE THREAD

**Issue by sangramgh01** [pavanpkulkarni/Spark_Streaming_Examples#1]
Hi,
Please check the below issue while running the scala application in eclipse.

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/04/09 17:46:40 WARN Utils: Your hostname, sangram-VirtualBox resolves to a loopback address: 127.0.0.1; using 10.0.2.15 instead (on interface eth0)
19/04/09 17:46:40 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
19/04/09 17:46:40 INFO SparkContext: Running Spark version 2.3.0
19/04/09 17:46:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/09 17:46:42 INFO SparkContext: Submitted application: Socket_Streaming
19/04/09 17:46:42 INFO SecurityManager: Changing view acls to: orienit
19/04/09 17:46:42 INFO SecurityManager: Changing modify acls to: orienit
19/04/09 17:46:42 INFO SecurityManager: Changing view acls groups to: 
19/04/09 17:46:42 INFO SecurityManager: Changing modify acls groups to: 
19/04/09 17:46:42 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(orienit); groups with view permissions: Set(); users  with modify permissions: Set(orienit); groups with modify permissions: Set()
19/04/09 17:46:42 INFO Utils: Successfully started service 'sparkDriver' on port 37927.
19/04/09 17:46:42 INFO SparkEnv: Registering MapOutputTracker
19/04/09 17:46:42 INFO SparkEnv: Registering BlockManagerMaster
19/04/09 17:46:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/04/09 17:46:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/04/09 17:46:42 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-37ce2e71-0ea3-42d9-a1b9-d08d04e98e51
19/04/09 17:46:42 INFO MemoryStore: MemoryStore started with capacity 954.5 MB
19/04/09 17:46:42 INFO SparkEnv: Registering OutputCommitCoordinator
19/04/09 17:46:43 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/04/09 17:46:43 INFO Utils: Successfully started service 'SparkUI' on port 4041.
19/04/09 17:46:43 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.0.2.15:4041
19/04/09 17:46:44 INFO Executor: Starting executor ID driver on host localhost
19/04/09 17:46:44 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39724.
19/04/09 17:46:44 INFO NettyBlockTransferService: Server created on 10.0.2.15:39724
19/04/09 17:46:44 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/04/09 17:46:44 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 39724, None)
19/04/09 17:46:44 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:39724 with 954.5 MB RAM, BlockManagerId(driver, 10.0.2.15, 39724, None)
19/04/09 17:46:44 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 39724, None)
19/04/09 17:46:44 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 39724, None)
**Exception in thread "main" java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.internal.SessionState':**
    at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:981)
    at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:110)
    at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:109)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
    at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:878)
    at com.pavanpkulkarni.wordcount.SocketStreaming$.main(SocketStreaming.scala:9)
    at com.pavanpkulkarni.wordcount.SocketStreaming.main(SocketStreaming.scala)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:978)
    ... 12 more
Caused by: java.lang.AbstractMethodError
    at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
    at org.apache.spark.sql.internal.SharedState.initializeLogIfNecessary(SharedState.scala:38)
    at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
    at org.apache.spark.sql.internal.SharedState.log(SharedState.scala:38)
    at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
    at org.apache.spark.sql.internal.SharedState.logInfo(SharedState.scala:38)
    at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:69)
    at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
    at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:101)
    at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:100)
    at org.apache.spark.sql.internal.SessionState.<init>(SessionState.scala:157)
    ... 17 more
19/04/09 17:46:44 INFO SparkContext: Invoking stop() from shutdown hook
19/04/09 17:46:44 INFO SparkUI: Stopped Spark web UI at http://10.0.2.15:4041
19/04/09 17:46:44 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/04/09 17:46:44 INFO MemoryStore: MemoryStore cleared
19/04/09 17:46:44 INFO BlockManager: BlockManager stopped
19/04/09 17:46:44 INFO BlockManagerMaster: BlockManagerMaster stopped
19/04/09 17:46:44 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/04/09 17:46:44 INFO SparkContext: Successfully stopped SparkContext
19/04/09 17:46:44 INFO ShutdownHookManager: Shutdown hook called
19/04/09 17:46:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-b7301eb2-1a44-4ab7-9171-9f482faef3cb

**Comment by sangramgh01** [comment]
I have taken complete project from github and run.then it was worked fine for me.
thanks
